language: node_js
node_js:
  - '7'
env:
  global:
    - FIREBASE_MASTER: archvillain-86957
    - FIREBASE_STAGING: archvillain-staging
script:
- ./travis-deploy.sh
install:
- npm install -g firebase-tools
